SELECT ?x ?uf ?all
WHERE {
    {
		SELECT ?x (COUNT (DISTINCT ?auth) AS ?uf)
		WHERE {
			?x a bibo:AcademicArticle .
			?x vivo:dateTimeValue ?dv .
			?dv vivo:dateTime ?d .
			FILTER(regex(?d,"^2014"))
			?x vivo:informationResourceInAuthorship ?a .
			?a vivo:linkedAuthor ?auth .
			?auth a ufVivo:UFEntity .
		}
		GROUP BY ?x
	}
    {
		SELECT ?x (COUNT (DISTINCT ?auth) AS ?non_uf)
		WHERE {
			?x a bibo:AcademicArticle .
			?x vivo:dateTimeValue ?dv .
			?dv vivo:dateTime ?d .
			FILTER(regex(?d,"^2014"))
			?x vivo:informationResourceInAuthorship ?a .
			?a vivo:linkedAuthor ?auth .
		}
		GROUP BY ?x
    }
}