PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd:   <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>
PREFIX swrl:  <http://www.w3.org/2003/11/swrl#>
PREFIX swrlb: <http://www.w3.org/2003/11/swrlb#>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/0.7#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX c4o: <http://purl.org/spar/c4o/>
PREFIX dcelem: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX event: <http://purl.org/NET/c4dm/event.owl#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX geo: <http://aims.fao.org/aos/geopolitical.owl#>
PREFIX pvs: <http://vivoweb.org/ontology/provenance-support#>
PREFIX ero: <http://purl.obolibrary.org/obo/>
PREFIX scires: <http://vivoweb.org/ontology/scientific-research#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ufVivo: <http://vivo.ufl.edu/ontology/vivo-ufl/>
PREFIX vitro: <http://vitro.mannlib.cornell.edu/ns/vitro/public#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>

#
# Grants Query
#
SELECT ?uri (SAMPLE(DISTINCT ?xtitle) AS ?title) 
            (SAMPLE(DISTINCT ?s) AS ?sponsorid) 
			(SAMPLE(DISTINCT ?xgrantdirect) AS ?grantdirect) 
			(SAMPLE(DISTINCT ?xdsrnumber) AS ?dsrnumber) 
			(SAMPLE(DISTINCT ?xadmindept) AS ?admindept)
			(SAMPLE(DISTINCT ?xfundingorg) AS ?fundingorg)
			(SAMPLE(DISTINCT ?xstartdate) AS ?startdate) 
			(SAMPLE(DISTINCT ?xenddate) AS ?enddate) 
			(SAMPLE(DISTINCT ?xpiuri) AS ?piuri)
WHERE {
 ?uri a vivo:Grant .
 ?uri rdfs:label ?xtitle .
 OPTIONAL {?uri vivo:sponsorAwardId ?s .}
 OPTIONAL {?uri vivo:grantDirectCosts ?xgrantdirect .}
 OPTIONAL {?uri ufVivo:dsrNumber ?xdsrnumber .}
 OPTIONAL {?uri vivo:administeredBy ?d . ?d rdfs:label ?xadmindept .}
 OPTIONAL {?uri vivo:grantAwardedBy ?fa . ?fa rdfs:label ?xfundingorg .}
 OPTIONAL {?uri vivo:dateTimeInterval ?dti . ?dti vivo:start ?xstart . ?xstart vivo:dateTime ?xstartdate . ?dti vivo:end ?xend . ?xend vivo:dateTime ?xenddate .}
 OPTIONAL {?uri vivo:contributingRole ?role . ?role a vivo:PrincipalInvestigatorRole . ?role vivo:principalInvestigatorRoleOf ?xpiuri .}
}
GROUP BY ?uri